-- ===================================================
-- Supabase Schema for Vasantha Iron Works Reviews
-- Run this in your Supabase SQL Editor (1-Click Setup)
-- ===================================================

-- 1. Create the reviews table
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  location text,
  project_type text not null,
  rating int not null default 5 check (rating >= 1 and rating <= 5),
  comment text not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.reviews enable row level security;

-- 3. Policy: Allow anyone visiting the website to read reviews
create policy "Allow public to read reviews" 
on public.reviews 
for select 
using (true);

-- 4. Policy: Allow anyone visiting the website to submit a review
create policy "Allow public to submit reviews" 
on public.reviews 
for insert 
with check (true);

-- 5. Insert initial verified real projects (optional)
insert into public.reviews (name, location, project_type, rating, comment)
values
  ('School Committee', 'B/Athalapitiya Primary School', 'Curved Canopy Roofing Project', 5, 'Vasantha Iron Works completed our school curved canopy roofing with outstanding structural steel strength and precise welding. The team was reliable, punctual, and delivered exceptional durability.'),
  ('Mr. Samantha Silva', 'Diyathalawa', 'Veranda Safety Railing & Gate', 5, 'Exceptional craftsmanship on our veranda safety railing and integrated gate. The 2×2 and ¾ box bar construction is solid, perfectly aligned, and the black matte finish looks modern and elegant.'),
  ('Mr. K. Perera', 'Bandarawela', 'Vehicle Parking Canopy & Grills', 5, 'Quick quotation, transparent pricing, and robust materials. They fabricated our vehicle parking canopy and window security grills with heavy gauge steel. Reliable and highly recommended in the area.');
